from .pages import (
    Page,
    CART_PAGE,
    SLOTS_PAGE_BY_FOOD_SERVICE,
    SLOTS_PAGE_WF,
    SLOTS_PAGE_AF,
    DID_YOU_FORGET_PAGE,
    GUEST_PAGE,
    RECOMMENDATIONS_PAGE,
    SIGNED_IN_PAGE,
    SIGN_IN_AGAIN_PAGE,
    NO_PAGE,
    SUBSTITUTIONS_PAGE,
)
